# Generated by Django 3.2.24 on 2024-03-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jd_ents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jd_ents',
            old_name='worked_as',
            new_name='jobpost',
        ),
        migrations.AddField(
            model_name='jd_ents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
