# Generated by Django 3.2.24 on 2024-03-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240302_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jd_ents',
            old_name='education',
            new_name='degree',
        ),
    ]
